name: Go-static-analysis
on: [push, pull_request]
jobs:

  golangci:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: remove deployer container from dockerfile
        run: sed -ie '/End of builder/,+5d' ./docker/userspacecni/Dockerfile
      - name: Build the Docker image
        run: docker build . -f ./docker/userspacecni/Dockerfile -t userspacecni:latest
      - name: run container
        run: docker run --name userspacecni -itd userspacecni:latest bash
      - name: docker copy generated bin api files
        run: docker cp userspacecni:/root/userspace-cni-network-plugin/cnivpp ./

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.52.2

  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master

  hadolint:
    runs-on: ubuntu-latest
    name: Hadolint
    steps:
    - uses: actions/checkout@v3
    - uses: hadolint/hadolint-action@v3.1.0
      name: Run Hadolint
      with:
       dockerfile: ./docker/userspacecni/Dockerfile
       ignore: DL3008,DL3059

  go-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: remove deployer container from dockerfile
      run: sed -ie '/End of builder/,+5d' ./docker/userspacecni/Dockerfile
    - name: Build the Docker image
      run: docker build . -f ./docker/userspacecni/Dockerfile -t userspacecni:latest
    - name: run container
      run: docker run --name userspacecni -itd userspacecni:latest bash
    - name: docker copy generated bin api files
      run: docker cp userspacecni:/root/userspace-cni-network-plugin/cnivpp ./

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20.x

    - name: checkout dockerfile to avoid false diff
      run: git checkout ./docker/userspacecni/Dockerfile
    # if this fails, run go mod tidy
    - name: Check if module files are consistent with code
      run: go mod tidy && go get go.fd.io/govpp/binapigen/vppapi@v0.7.0 && git diff --exit-code #need package for bin api but not working with tidy

    # if this fails, run go mod vendor
    - name: Check if vendor directory is consistent with go modules
      run: go mod vendor && git diff --exit-code
